"""
PDF Structure Visualization
============================

Phase 2.3 - Quality Control

This module creates annotated PNG images showing:

    - Text block bounding boxes
    - Reading order
    - Structure classification
    - Header / Footer detection
    - Font size

It is a DEVELOPMENT / VALIDATION tool.

It does NOT modify the production PDF.
"""

from pathlib import Path

import fitz
from PIL import Image, ImageDraw, ImageFont

from app.models.document import (
    PageText,
)


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_SCALE = 2.0

DEFAULT_OUTPUT_DIR = Path(
    "data/validation"
)


# ============================================================
# MAIN FUNCTION
# ============================================================


def visualize_document_page(
    pdf_path: Path,
    page_data: PageText,
    output_path: Path,
    scale: float = DEFAULT_SCALE,
) -> Path:
    """
    Create an annotated PNG for one PDF page.

    Args:
        pdf_path:
            Path to original PDF.

        page_data:
            PageText object generated by Phase 2.2.

        output_path:
            Destination PNG file.

        scale:
            Rendering scale.

    Returns:
        Path to generated PNG.
    """

    # --------------------------------------------------------
    # Open PDF
    # --------------------------------------------------------

    document = fitz.open(
        pdf_path
    )

    try:

        page_index = (
            page_data.page_number - 1
        )

        if (
            page_index < 0
            or page_index >= len(document)
        ):

            raise ValueError(
                f"Invalid page number: "
                f"{page_data.page_number}"
            )

        page = document[
            page_index
        ]

        # ----------------------------------------------------
        # Render PDF page
        # ----------------------------------------------------

        matrix = fitz.Matrix(
            scale,
            scale,
        )

        pixmap = page.get_pixmap(
            matrix=matrix,
            alpha=False,
        )

        image = Image.frombytes(
            "RGB",
            [
                pixmap.width,
                pixmap.height,
            ],
            pixmap.samples,
        )

    finally:

        document.close()

    # --------------------------------------------------------
    # Prepare drawing
    # --------------------------------------------------------

    draw = ImageDraw.Draw(
        image
    )

    font = get_font(
        size=14
    )

    small_font = get_font(
        size=11
    )

    # --------------------------------------------------------
    # Draw every text block
    # --------------------------------------------------------

    for block in page_data.blocks:

        draw_block(
            draw=draw,
            block=block,
            scale=scale,
            font=font,
            small_font=small_font,
        )

    # --------------------------------------------------------
    # Add page information
    # --------------------------------------------------------

    draw_page_information(
        draw=draw,
        page_data=page_data,
        font=font,
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    image.save(
        output_path,
        format="PNG",
    )

    return output_path


# ============================================================
# DRAW BLOCK
# ============================================================


def draw_block(
    draw: ImageDraw.ImageDraw,
    block,
    scale: float,
    font,
    small_font,
) -> None:
    """
    Draw one text block.
    """

    # --------------------------------------------------------
    # Coordinates
    # --------------------------------------------------------

    x0 = block.x0 * scale
    y0 = block.y0 * scale
    x1 = block.x1 * scale
    y1 = block.y1 * scale

    # --------------------------------------------------------
    # Determine label
    # --------------------------------------------------------

    structure = (
        block.structure
        or "unknown"
    )

    order = (
        block.reading_order
        or 0
    )

    label = (
        f"{order:02d} | "
        f"{structure.upper()}"
    )

    if block.is_header:

        label += " | HEADER"

    elif block.is_footer:

        label += " | FOOTER"

    # --------------------------------------------------------
    # Bounding box
    # --------------------------------------------------------

    draw.rectangle(
        [
            x0,
            y0,
            x1,
            y1,
        ],
        outline="red",
        width=3,
    )

    # --------------------------------------------------------
    # Label background
    # --------------------------------------------------------

    bbox = draw.textbbox(
        (0, 0),
        label,
        font=small_font,
    )

    label_width = (
        bbox[2] - bbox[0]
    )

    label_height = (
        bbox[3] - bbox[1]
    )

    label_x = x0

    label_y = max(
        0,
        y0 - label_height - 4,
    )

    draw.rectangle(
        [
            label_x,
            label_y,
            label_x + label_width + 8,
            label_y + label_height + 4,
        ],
        fill="white",
        outline="red",
    )

    draw.text(
        (
            label_x + 4,
            label_y + 2,
        ),
        label,
        fill="black",
        font=small_font,
    )

    # --------------------------------------------------------
    # Font information
    # --------------------------------------------------------

    if block.font_size:

        font_info = (
            f"{block.font_size:.1f} pt"
        )

        draw.text(
            (
                x0,
                y1 + 2,
            ),
            font_info,
            fill="black",
            font=small_font,
        )


# ============================================================
# PAGE INFORMATION
# ============================================================


def draw_page_information(
    draw: ImageDraw.ImageDraw,
    page_data: PageText,
    font,
) -> None:
    """
    Draw page-level information.
    """

    text = (
        f"PAGE {page_data.page_number}"
        f"   |   "
        f"BLOCKS: {len(page_data.blocks)}"
        f"   |   "
        f"SIZE: "
        f"{page_data.width:.0f} x "
        f"{page_data.height:.0f}"
    )

    draw.rectangle(
        [
            10,
            10,
            500,
            40,
        ],
        fill="white",
        outline="black",
    )

    draw.text(
        (
            15,
            15,
        ),
        text,
        fill="black",
        font=font,
    )


# ============================================================
# FONT
# ============================================================


def get_font(
    size: int,
):
    """
    Try to load a standard font.

    Falls back to Pillow's default font
    if Arial is unavailable.
    """

    windows_fonts = [
        Path(
            r"C:\Windows\Fonts\arial.ttf"
        ),
        Path(
            r"C:\Windows\Fonts\segoeui.ttf"
        ),
    ]

    for font_path in windows_fonts:

        if font_path.exists():

            return ImageFont.truetype(
                str(font_path),
                size,
            )

    return ImageFont.load_default()


# ============================================================
# DOCUMENT HELPER
# ============================================================


def visualize_page(
    pdf_path: Path,
    pages: list[PageText],
    page_number: int,
    output_dir: Path = DEFAULT_OUTPUT_DIR,
) -> Path:
    """
    Convenience function for visualizing
    a specific page.
    """

    if not pages:

        raise ValueError(
            "No extracted pages available."
        )

    page_data = next(
        (
            page
            for page in pages
            if page.page_number
            == page_number
        ),
        None,
    )

    if page_data is None:

        raise ValueError(
            f"Page {page_number} "
            f"not found."
        )

    output_path = (
        output_dir
        / (
            f"page_"
            f"{page_number:03d}.png"
        )
    )

    return visualize_document_page(
        pdf_path=pdf_path,
        page_data=page_data,
        output_path=output_path,
    )
